import { test, before } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { lookup, searchEntries, buildIndex, isProperKey, wordsContainingChar } from '../src/lib/dict-core.js'

// cedict.json is regenerated by `npm run build:dict` (pretest), merging the
// committed CedPane cache (assets/cedpane/cedpane.json) as proper-noun entries.
const __dirname = dirname(fileURLToPath(import.meta.url))
let DB, INDEX

before(() => {
  DB = JSON.parse(readFileSync(resolve(__dirname, '../src/data/cedict.json'), 'utf8'))
  INDEX = buildIndex(DB)
})

test('cedpane: the merge ran and tagged proper-noun keys', () => {
  assert.ok(DB.cedpane > 50000, `expected tens of thousands of CedPane keys, got ${DB.cedpane}`)
  // every CedPane sense carries the proper flag (1) at index 4
  const sp = DB.entries['声田']
  assert.ok(sp && sp[0][4] === 1, 'expected the CedPane proper-noun flag on 声田')
})

test('cedpane: a CedPane-only name resolves (Spotify -> 声田)', () => {
  const e = lookup(DB, '声田')
  assert.ok(e, '声田 should resolve')
  assert.equal(e.q, '声田')
  assert.equal(e.proper, true, '声田 is a proper noun')
  assert.equal(e.trad, '聲田')
  assert.ok(e.defs.join(' ').includes('Spotify'))
  // the pinyin is CedPane's already-tone-marked form, passed through unchanged
  assert.equal(e.pinyin, 'Shēngtián')
})

test('cedpane: a name resolves from its traditional form too', () => {
  assert.equal(lookup(DB, '聲田').q, '声田')
})

test('cedpane: isProperKey distinguishes names from everyday words', () => {
  assert.equal(isProperKey(DB, '声田'), true)
  assert.equal(isProperKey(DB, '你好'), false)
  assert.equal(isProperKey(DB, '中国'), false)
  assert.equal(isProperKey(DB, '中'), false)
})

test('cedpane: existing CC-CEDICT lookups are unchanged by the merge', () => {
  // the merge skips simplified forms CC-CEDICT already covers, so common entries
  // never gain a proper-noun sense and keep their exact primary reading
  assert.equal(lookup(DB, '你好').defs[0].toLowerCase().includes('hello'), true)
  assert.equal(lookup(DB, '中国').defs[0], 'China')
  assert.equal(lookup(DB, '中国').proper, undefined)
  assert.equal(lookup(DB, '台湾').defs[0], 'Taiwan')
  assert.equal(lookup(DB, '钟').proper, undefined)
  assert.match(lookup(DB, '钟').defs.join(' '), /bell|clock/i)
  // an HSK word that only exists via CedPane is treated as a normal word, not a name
  assert.equal(isProperKey(DB, '新媒体'), false, '新媒体 is HSK vocab, not a proper noun')
  assert.equal(lookup(DB, '新媒体').hsk, 6)
})

test('cedpane: a common word outranks a proper noun in search', () => {
  // 中国 (China) must beat any proper noun for the hanzi query 中国
  const rows = searchEntries(DB, INDEX, '中国', 30)
  assert.equal(rows[0].q, '中国')
  const firstProper = rows.findIndex((r) => r.proper)
  const lastCommon = rows.reduce((m, r, i) => (r.proper ? m : i), -1)
  assert.ok(firstProper === -1 || firstProper > lastCommon, 'no proper noun may rank above an ordinary word')

  // English "hello": 你好 leads, no proper noun beats it
  const hello = searchEntries(DB, INDEX, 'hello', 30)
  const ni = hello.findIndex((r) => r.q === '你好')
  const firstProperHello = hello.findIndex((r) => r.proper)
  assert.ok(ni >= 0, '你好 should appear for "hello"')
  assert.ok(firstProperHello === -1 || firstProperHello > ni, '你好 must rank above any proper noun')
})

test('cedpane: an exact full match still surfaces the proper noun', () => {
  // exact hanzi: the name is the only/leading result even though it is a proper noun
  assert.equal(searchEntries(DB, INDEX, '声田', 30)[0].q, '声田')
  // exact English name: the proper noun is findable
  assert.ok(searchEntries(DB, INDEX, 'Spotify', 30).some((r) => r.q === '声田'))
})

// ---- precise ranking rules on a tiny synthetic DB (no corpus dependence) ----

function tinyDb() {
  return {
    entries: {
      银行: [['yin2hang2', ['bank (finance)'], 0]], // common, HSK
      河堤: [['he2di1', ['embankment; bank'], 0]], // common, non-HSK
      班克斯: [['ban1ke4si1', ['Banks (place); bank'], 0, 0, 1]], // proper noun (flag at idx 4)
    },
    hsk: { 银行: '3' },
    pos: {},
    hskSenses: {},
    chars: {},
    charGloss: {},
    tradToSimp: {},
  }
}

test('ranking: proper noun sinks below ordinary words at equal match quality', () => {
  const db = tinyDb()
  const index = buildIndex(db)
  const rows = searchEntries(db, index, 'bank', 30)
  const idx = (q) => rows.findIndex((r) => r.q === q)
  assert.ok(idx('银行') >= 0 && idx('河堤') >= 0 && idx('班克斯') >= 0, 'all three match "bank"')
  assert.ok(idx('班克斯') > idx('银行'), 'proper noun below the HSK word')
  assert.ok(idx('班克斯') > idx('河堤'), 'proper noun below the ordinary word')
  assert.equal(rows[rows.length - 1].q, '班克斯', 'the proper noun is last')
})

test('ranking: an exact full match exempts the proper noun from demotion', () => {
  const db = tinyDb()
  const index = buildIndex(db)
  // exact hanzi for the name surfaces it first despite the proper-noun penalty
  assert.equal(searchEntries(db, index, '班克斯', 30)[0].q, '班克斯')
  assert.equal(lookup(db, '班克斯').proper, true)
  assert.equal(lookup(db, '银行').proper, undefined)
})

test('ranking: the word family keeps names below ordinary words', () => {
  const db = {
    entries: {
      中学: [['zhong1xue2', ['middle school'], 0]],
      中庸: [['zhong1yong1', ['the Doctrine of the Mean'], 0]],
      中本聪: [['zhong1ben3cong1', ['Satoshi Nakamoto'], 0, 0, 1]], // proper noun containing 中
    },
    hsk: { 中学: '2' },
    pos: {},
    hskSenses: {},
    chars: {},
    charGloss: {},
    tradToSimp: {},
  }
  const index = buildIndex(db)
  const fam = wordsContainingChar(db, index, '中', {})
  const order = fam.map((r) => r.q)
  assert.ok(order.includes('中本聪'), 'the name is part of the family')
  assert.equal(order[order.length - 1], '中本聪', 'but it sits last, below ordinary words')
})
