import { test, before } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { lookup, segmentLongest, searchEntries, compMeaning, buildIndex, hskWordsUpTo, hskWordsAtBand, hskRank } from '../src/lib/dict-core.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
let DB, INDEX

before(() => {
  // cedict.json is generated by `npm run build:dict` (run via pretest)
  DB = JSON.parse(readFileSync(resolve(__dirname, '../src/data/cedict.json'), 'utf8'))
  INDEX = buildIndex(DB) // same index the runtime builds in loadDict()
})

test('lookup: multi-char word', () => {
  const e = lookup(DB, '你好')
  assert.equal(e.type, 'word')
  assert.equal(e.pinyin, 'nǐ hǎo')
  assert.deepEqual(e.chars, ['你', '好'])
  assert.ok(e.defs.join(' ').toLowerCase().includes('hello'))
})

test('lookup: homograph exposes alternate readings', () => {
  const e = lookup(DB, '好')
  assert.equal(e.type, 'char')
  assert.ok(e.alts.length >= 1, 'expected a 4th-tone hào reading under alts')
  assert.ok(e.alts.some((a) => a.pinyin === 'hào'))
})

test('lookup: simplified input leads with a real meaning, not a variant/surname', () => {
  // plain simplified input (no specific traditional form) should surface the
  // common meaning as primary, demoting "variant of …" and surname-only readings
  const taiwan = lookup(DB, '台湾')
  assert.equal(taiwan.defs[0], 'Taiwan', '台湾 primary should be "Taiwan", not "variant of 臺灣"')

  const zhong = lookup(DB, '钟')
  assert.match(zhong.defs.join(' '), /bell|clock/i, '钟 primary should be bell/clock, not surname/cup')
  assert.ok(!/^surname\b/i.test(zhong.defs[0]), '钟 primary must not be the surname reading')

  const gan = lookup(DB, '干')
  assert.equal(gan.defs[0], 'dry', '干 primary should be "dry", not "old variant of 乾"')

  // a demoted reading is not dropped — it moves under "Other readings"
  assert.ok(taiwan.alts.some((a) => a.defs.some((d) => /variant of/i.test(d))),
    'the variant reading should still be available under alts')
})

test('lookup: a requested traditional form still overrides value ranking', () => {
  // 髮 is a specific traditional form -> its reading wins regardless of penalty
  assert.equal(lookup(DB, '髮').defs[0], 'hair')
  // common simplified meanings unaffected by the ranking
  assert.equal(lookup(DB, '面').defs[0], 'face')
  assert.equal(lookup(DB, '发').defs[0], 'to send out')
})

test('lookup: HSK level + part of speech attached', () => {
  const xuexi = lookup(DB, '学习')
  assert.equal(xuexi.hsk, 1)
  assert.equal(xuexi.pos, 'verb')
  const zhongguo = lookup(DB, '中国')
  assert.equal(zhongguo.hsk, 1)
  assert.equal(zhongguo.pos, 'noun')
})

test('lookup: attaches the official HSK gloss senses when available', () => {
  const xuexi = lookup(DB, '学习').hskSenses
  assert.equal(xuexi.length, 1)
  assert.equal(xuexi[0].def, 'to learn; to study')
  assert.equal(xuexi[0].lvl, 1)
  assert.equal(xuexi[0].pos, 'verb')

  // a word with multiple distinct HSK meanings exposes them all, each with level + POS
  const hui = lookup(DB, '会').hskSenses
  assert.ok(hui.length >= 2, 'expected 会 to carry multiple HSK senses')
  assert.ok(hui.some((s) => /can/.test(s.def)) && hui.some((s) => /meeting/.test(s.def)))
  for (const s of hui) assert.ok(s.lvl && typeof s.def === 'string')

  // a word that isn't in the HSK lists carries no senses
  const nonHsk = Object.keys(DB.entries).find((k) => !(DB.hsk && DB.hsk[k]))
  assert.equal(lookup(DB, nonHsk).hskSenses, undefined)
})

test('hskWordsUpTo: returns HSK words at or below a level as [word, rank]', () => {
  const upTo3 = hskWordsUpTo(DB, 3)
  const words = new Map(upTo3)
  // common low-level words are included, with the right rank
  assert.equal(words.get('学习'), 1)
  assert.equal(words.get('中国'), 1)
  // every returned rank is within bounds, and the 7–9 band never leaks in at ≤3
  for (const [, rank] of upTo3) assert.ok(rank >= 1 && rank <= 3)
  // a higher level returns a superset, and only "all" (7) surfaces the 7–9 band
  assert.ok(hskWordsUpTo(DB, 6).length > upTo3.length)
  assert.ok(!hskWordsUpTo(DB, 6).some(([, r]) => r === 7))
  assert.ok(hskWordsUpTo(DB, 7).some(([, r]) => r === 7))
  // level 0 / falsy -> nothing
  assert.equal(hskWordsUpTo(DB, 0).length, 0)
})

test('hskWordsUpTo: works on a bare { hsk } object (the worker shape)', () => {
  // the service worker now feeds it only the small hsk-words map, not full DB
  const bare = { hsk: { 学习: '1', 经济: '4', 巍峨: '7-9' } }
  const upTo4 = new Map(hskWordsUpTo(bare, 4))
  assert.equal(upTo4.get('学习'), 1)
  assert.equal(upTo4.get('经济'), 4)
  assert.equal(upTo4.has('巍峨'), false, '7–9 band excluded at ≤4')
  assert.ok(new Map(hskWordsUpTo(bare, 7)).get('巍峨') === 7)
})

test('lookup: HSK 3.0 advanced band shows as "7-9"', () => {
  const word = Object.keys(DB.hsk).find((w) => DB.hsk[w] === '7-9')
  assert.ok(word, 'expected some 7-9 band words')
  assert.equal(lookup(DB, word).hsk, '7-9')
})

test('lookup: single-char decomposition (radical/components/strokes)', () => {
  const e = lookup(DB, '好')
  assert.equal(e.radical.char, '女')
  assert.equal(e.radical.meaning, 'woman')
  assert.equal(e.strokes, 6)
  assert.ok(e.components.includes('子'))
  assert.ok(!e.components.includes('女'), 'radical is shown separately, not duplicated in components')
})

test('lookup: unknown returns null', () => {
  assert.equal(lookup(DB, 'zzzz'), null)
  assert.equal(lookup(DB, ''), null)
})

test('segmentLongest: greedy longest match', () => {
  assert.deepEqual(segmentLongest(DB, '新闻是'), { word: '新闻', len: 2 })
  assert.deepEqual(segmentLongest(DB, '学习中文'), { word: '学习', len: 2 })
  assert.deepEqual(segmentLongest(DB, '我'), { word: '我', len: 1 })
})

test('searchEntries: hanzi, english, toneless pinyin', () => {
  const han = searchEntries(DB, INDEX, '中国')
  assert.ok(han.some((r) => r.q === '中国'))

  const eng = searchEntries(DB, INDEX, 'hello')
  assert.ok(eng.some((r) => r.q === '你好'))

  const py = searchEntries(DB, INDEX, 'nihao')
  assert.ok(py.some((r) => r.q === '你好'))

  assert.deepEqual(searchEntries(DB, INDEX, ''), [])
})

test('searchEntries: result rows carry hsk level', () => {
  const rows = searchEntries(DB, INDEX, '中国')
  const row = rows.find((r) => r.q === '中国')
  assert.equal(row.hsk, 1)
})

test('lookup: measure words surfaced with tone-marked pinyin', () => {
  const e = lookup(DB, '猫') // cat — measure word 只 zhī
  assert.ok(Array.isArray(e.measures) && e.measures.length >= 1)
  assert.ok(e.measures.some((m) => m.includes('只 zhī')))
  assert.ok(!e.measures.some((m) => /\d/.test(m)), 'no numbered pinyin in measures')
})

test('lookup: multiple readings grouped into alts', () => {
  const de = lookup(DB, '的') // de / dī / dí / dì
  assert.ok(de.alts.length >= 2)
  const readings = [de.pinyin, ...de.alts.map((a) => a.pinyin)]
  assert.ok(readings.includes('de') && readings.includes('dì'))
})

test('lookup: words have no single-char decomposition', () => {
  const e = lookup(DB, '你好')
  assert.equal(e.radical, undefined)
  assert.equal(e.components, undefined)
  assert.equal(e.strokes, undefined)
})

test('compMeaning: gloss for a component char, empty for unknown', () => {
  assert.equal(compMeaning(DB, '女'), 'woman')
  assert.equal(compMeaning(DB, '☃'), '')
})

test('segmentLongest: respects maxLen', () => {
  // only the first 2 chars are considered, so 中国人 -> 中国
  assert.deepEqual(segmentLongest(DB, '中国人', 2), { word: '中国', len: 2 })
})

test('searchEntries: exact match ranks first; limit respected', () => {
  const rows = searchEntries(DB, INDEX, '好')
  assert.equal(rows[0].q, '好') // exact (rank 0, shortest) wins
  assert.ok(searchEntries(DB, INDEX, '的', 3).length <= 3)
})

test('index integrity: cedict.json carries all merged maps', () => {
  for (const k of ['entries', 'hsk', 'pos', 'chars', 'charGloss', 'tradToSimp']) {
    assert.ok(DB[k] && Object.keys(DB[k]).length > 0, `expected non-empty ${k}`)
  }
  assert.ok(Object.keys(DB.entries).length > 100000, 'expected the full CC-CEDICT index')
})

test('lookup: one-to-many traditional forms resolve to the right reading', () => {
  // 发 has two traditional sources with different readings/meanings
  const fa = lookup(DB, '發')
  assert.equal(fa.q, '发')
  assert.equal(fa.trad, '發')
  assert.ok(fa.defs.join(' ').toLowerCase().includes('send'))
  const fa2 = lookup(DB, '髮')
  assert.equal(fa2.q, '发')
  assert.equal(fa2.trad, '髮')
  assert.equal(fa2.pinyin, 'fà')
  assert.ok(fa2.defs.join(' ').toLowerCase().includes('hair'))

  // 麵 (noodles) shares the reading miàn with 面 (face) but is a distinct sense
  const mian = lookup(DB, '麵')
  assert.equal(mian.q, '面')
  assert.equal(mian.trad, '麵')
  assert.ok(mian.defs.join(' ').toLowerCase().match(/noodle|flour/))

  // 鐘 (bell) shares zhōng with 鍾 (surname/cup) under simplified 钟
  const zhong = lookup(DB, '鐘')
  assert.equal(zhong.q, '钟')
  assert.equal(zhong.trad, '鐘')
  assert.ok(zhong.defs.join(' ').toLowerCase().includes('bell'))

  // 臺灣 must resolve (previously only 台灣 was reachable) and show "Taiwan"
  const tw = lookup(DB, '臺灣')
  assert.equal(tw.q, '台湾')
  assert.equal(tw.trad, '臺灣')
  assert.ok(tw.defs.join(' ').toLowerCase().includes('taiwan'))
})

test('lookup: a simplified form that is its own entry is not redirected', () => {
  // 后 is both a real simplified entry and the traditional source of 後 — looking
  // it up must return 后 itself, not redirect via tradToSimp
  const hou = lookup(DB, '后')
  assert.equal(hou.q, '后')
  assert.equal(hou.trad, undefined)
})

test('searchEntries: high-selectivity queries stay fast via the index (full-scan regression guard)', () => {
  // The old code scanned all ~121k keys for every query (~40-95ms). These queries
  // map to a small candidate set, so indexed search is reliably sub-millisecond; a
  // regression to a full scan would jump to tens of ms and trip the ceiling. Median
  // over several runs + a generous bound keeps this from being wall-clock flaky.
  // (Very common English words like "to" are intentionally not timed — they match
  // tens of thousands of definitions no matter how search is implemented.)
  const medianMs = (q) => {
    for (let i = 0; i < 3; i++) searchEntries(DB, INDEX, q) // warm up
    const s = []
    for (let i = 0; i < 11; i++) {
      const t0 = process.hrtime.bigint()
      searchEntries(DB, INDEX, q)
      s.push(Number(process.hrtime.bigint() - t0) / 1e6)
    }
    return s.sort((a, b) => a - b)[5]
  }
  for (const q of ['zhong', 'hello', 'nihao', '中国']) {
    const ms = medianMs(q)
    assert.ok(ms < 10, `indexed search "${q}" median ${ms.toFixed(2)}ms — possible regression to a full scan`)
  }
})

test('lookup: traditional input resolves to the simplified entry', () => {
  const a = lookup(DB, '中國') // traditional of 中国
  assert.equal(a.q, '中国')
  assert.equal(a.trad, '中國')
  assert.ok(a.defs.join(' ').toLowerCase().includes('china'))

  const b = lookup(DB, '學習') // traditional of 学习
  assert.equal(b.q, '学习')
  assert.ok(b.defs.join(' ').toLowerCase().includes('learn'))
})

test('lookup: simplified entry surfaces its traditional form when it differs', () => {
  assert.equal(lookup(DB, '学习').trad, '學習')
  assert.equal(lookup(DB, '中国').trad, '中國')
  // a char whose forms are identical has no separate trad
  assert.equal(lookup(DB, '人').trad, undefined)
})

test('segmentLongest: matches a traditional run via tradToSimp', () => {
  // 新聞 is the traditional form of 新闻 (news); the run should segment as 2 chars
  assert.deepEqual(segmentLongest(DB, '新聞是'), { word: '新聞', len: 2 })
})

test('searchEntries: pinyin "zhong" surfaces 中 ahead of rare characters', () => {
  const rows = searchEntries(DB, INDEX, 'zhong')
  const idx = rows.findIndex((r) => r.q === '中')
  assert.ok(idx >= 0 && idx < 5, `中 should rank near the top, got index ${idx}`)
  // rare homophone characters must not outrank the common one
  for (const rare of ['伀', '尰', '彸']) {
    const ri = rows.findIndex((r) => r.q === rare)
    if (ri >= 0) assert.ok(ri > idx, `${rare} should not rank above 中`)
  }
})

test('searchEntries: english "hello" ranks 你好 above 喂', () => {
  const rows = searchEntries(DB, INDEX, 'hello')
  const ni = rows.findIndex((r) => r.q === '你好')
  const wei = rows.findIndex((r) => r.q === '喂')
  assert.ok(ni >= 0, '你好 should appear for "hello"')
  assert.ok(ni < wei || wei < 0, '你好 should rank above 喂')
})

test('searchEntries: "nihao" finds 你好 first', () => {
  assert.equal(searchEntries(DB, INDEX, 'nihao')[0].q, '你好')
})

test('searchEntries: tiny english query "a" returns only whole-word def matches', () => {
  const rows = searchEntries(DB, INDEX, 'a')
  // every row must have a definition (or pinyin) where "a" stands alone as a
  // token — no rare-character substring noise like a def merely containing "a"
  for (const r of rows.slice(0, 10)) {
    const senses = DB.entries[r.q]
    const tokenHit = senses.some((s) => (s[1] || []).some((d) => d.toLowerCase().split(/[^a-z0-9]+/).includes('a')))
    const pinyinHit = senses.some((s) => s[0].replace(/u:/g, 'u').replace(/[0-9\s]/g, '').toLowerCase() === 'a')
    assert.ok(tokenHit || pinyinHit, `unexpected noisy match for "a": ${r.q}`)
  }
})

test('paragraph segmentation: greedy segmentLongest + lookup loop (the worker shape)', () => {
  // mirrors the service worker's `segment` handler: walk a paragraph, greedily
  // take the longest dictionary word at each step, attach tone-marked pinyin for
  // the reader's ruby. Robust to whether 喝茶 is itself a headword.
  const para = '我喜欢喝茶'
  const out = []
  let rest = [...para]
  while (rest.length) {
    const seg = segmentLongest(DB, rest.join(''))
    const e = lookup(DB, seg.word)
    out.push({ t: seg.word, py: e ? e.pinyin : '' })
    rest = rest.slice(seg.len)
  }
  assert.equal(out.map((o) => o.t).join(''), para, 'tokens reconstruct the paragraph')
  assert.ok(out.some((o) => o.t === '喜欢'), '喜欢 is segmented as one word, not two chars')
  assert.ok(out.every((o) => o.py && o.py.length), 'every token resolves to non-empty pinyin')
  assert.ok(out.find((o) => o.t === '喜欢').py.startsWith('xǐ'), '喜欢 pinyin is tone-marked')
})

test('hskWordsAtBand: returns exactly one band (not cumulative), powers the per-level decks', () => {
  const b3 = hskWordsAtBand(DB, 3)
  assert.ok(b3.length > 0, 'HSK band 3 is non-empty')
  for (const [w, rank] of b3) {
    assert.equal(rank, 3)
    assert.equal(hskRank(DB.hsk[w]), 3, `${w} is actually a band-3 word`)
  }
  // band 1 is the lowest band, so "at band 1" equals "up to band 1"
  assert.equal(hskWordsAtBand(DB, 1).length, hskWordsUpTo(DB, 1).length)
  // band 7 captures the advanced 7–9 set, stored as the string "7-9"
  const b7 = hskWordsAtBand(DB, 7)
  assert.ok(b7.length > 0, 'HSK 7–9 band is non-empty')
  for (const [w] of b7) assert.equal(DB.hsk[w], '7-9')
  // guard: no band/zero input returns nothing
  assert.deepEqual(hskWordsAtBand(DB, 0), [])
})
