import { test, before } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

// Guards the HSK ingest pipeline: convert-hsk.mjs (assets/hsk-vocab/*.xls ->
// hsk-data.json) and the build-dict merge into cedict.json. These are the exact
// invariants that broke repeatedly: per-band counts, decollapsed senses, pinyin,
// multi-band words, and words absent from CC-CEDICT.

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

// Each band's sense count must equal its vocab-list row count. Bump these only
// when the committed assets/hsk-vocab/*.xls lists themselves change.
const EXPECTED_BAND_COUNTS = { 1: 300, 2: 200, 3: 500, 4: 1000, 5: 1600, 6: 1800, '7-9': 5600 }

let HSK, DB

before(() => {
  HSK = JSON.parse(readFileSync(resolve(root, 'assets/hsk-vocab/hsk-data.json'), 'utf8'))
  // cedict.json is generated by `npm run build:dict` (run via pretest)
  DB = JSON.parse(readFileSync(resolve(root, 'src/data/cedict.json'), 'utf8'))
})

function bandCounts(senseMap) {
  const counts = {}
  for (const info of Object.values(senseMap)) {
    for (const s of info.senses || info) counts[String(s.lvl)] = (counts[String(s.lvl)] || 0) + 1
  }
  return counts
}

test('hsk-data.json: every sense carries lvl, pos, def and pinyin', () => {
  for (const [word, info] of Object.entries(HSK)) {
    assert.ok(info.senses && info.senses.length, `${word} has senses`)
    for (const s of info.senses) {
      assert.ok(s.lvl === '7-9' || (s.lvl >= 1 && s.lvl <= 6), `${word} sense lvl valid (${s.lvl})`)
      assert.equal(typeof s.def, 'string'); assert.ok(s.def.length, `${word} sense has a gloss`)
      assert.equal(typeof s.pos, 'string')
      assert.equal(typeof s.py, 'string') // column B pinyin parsed in (may be empty for a rare row)
    }
    // primary lvl/pos is the lowest-band sense
    assert.equal(info.lvl, info.senses[0].lvl)
  }
})

test('hsk-data.json: per-band sense count equals the vocab-list row count (decollapsed)', () => {
  const counts = bandCounts(HSK)
  for (const [band, want] of Object.entries(EXPECTED_BAND_COUNTS)) {
    assert.equal(counts[band], want, `HSK ${band} has ${want} senses`)
  }
})

test('multi-band word: 会 is "can" at HSK 1 and "meeting" at HSK 3', () => {
  const senses = HSK['会'].senses
  const lvls = new Set(senses.map((s) => String(s.lvl)))
  assert.ok(lvls.has('1') && lvls.has('3'), '会 appears at bands 1 and 3')
  assert.ok(senses.some((s) => s.lvl === 1 && /can/.test(s.def)))
  assert.ok(senses.some((s) => String(s.lvl) === '3' && /meeting/.test(s.def)))
})

test('decollapse: a POS-ambiguous word keeps a sense per reading (花 verb + noun)', () => {
  // 花 sits in HSK 2 as both [verb] spend and [noun] flower — both must survive
  const at2 = HSK['花'].senses.filter((s) => String(s.lvl) === '2')
  assert.ok(at2.length >= 2, '花 keeps both HSK-2 senses')
  assert.ok(new Set(at2.map((s) => s.pos)).size > 1, '花 senses span more than one POS')
})

test('build-dict: cedict.json hskSenses preserves the full set incl. pinyin', () => {
  // counts must survive the merge so the flashcards deck size matches the lists
  const counts = bandCounts(DB.hskSenses)
  for (const [band, want] of Object.entries(EXPECTED_BAND_COUNTS)) {
    assert.equal(counts[band], want, `cedict HSK ${band} has ${want} senses`)
  }
  assert.equal(typeof DB.hskSenses['会'][0].py, 'string')
  assert.ok(DB.hskSenses['会'][0].py.length, '会 carries pinyin into cedict.json')
})

test('build-dict: HSK words absent from CC-CEDICT still ship their senses', () => {
  // 新能源 ("new energy") is an HSK-6 word with no CC-CEDICT entry; the flashcards
  // deck is built from hskSenses, so it must still be present there
  assert.ok(DB.hskSenses['新能源'], '新能源 kept in hskSenses despite no cedict entry')
  assert.equal(DB.hsk['新能源'], undefined, 'but it stays out of the cedict-only hsk map')
})
