// HSK-1 vocabulary data · 300 words extracted from HSK-1.xls
// Each entry has a stable integer id used as the localStorage key in users.js
window.HSK1 = [
  {"id": 1, "w": "爱", "p": "ài", "m": "to love", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 2, "w": "八", "p": "bā", "m": "eight", "pos": "数", "lv": "YCT1,YCT3,HSK1,New HSK1"},
  {"id": 3, "w": "吧", "p": "ba", "m": "[makes a suggestion, e.g. \"Let's …\"]", "pos": "助", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 4, "w": "爸爸", "p": "bà ba", "m": "father", "pos": "名", "lv": "YCT1,YCT4,HSK1,New HSK1"},
  {"id": 5, "w": "百", "p": "bǎi", "m": "hundred", "pos": "数", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 6, "w": "白天", "p": "bái tiān", "m": "daytime", "pos": "名", "lv": "New HSK1"},
  {"id": 7, "w": "半", "p": "bàn", "m": "half", "pos": "数", "lv": "YCT3,YCT4,HSK3,New HSK1"},
  {"id": 8, "w": "包子", "p": "bāo zi", "m": "bao zi [steamed stuffed bun]", "pos": "名", "lv": "YCT2,HSK4,New HSK1"},
  {"id": 9, "w": "杯子", "p": "bēi zi", "m": "cup; glass; mug", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 10, "w": "本", "p": "běn", "m": "root; [measure word for books]", "pos": "量", "lv": "YCT3,YCT4,HSK1,New HSK1,New HSK5"},
  {"id": 11, "w": "边", "p": "biān", "m": "edge", "pos": "名、后缀", "lv": "New HSK1"},
  {"id": 12, "w": "病", "p": "bìng", "m": "illness", "pos": "名、动", "lv": "New HSK1"},
  {"id": 13, "w": "不", "p": "bù", "m": "not; no", "pos": "副", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 14, "w": "不客气", "p": "bú kè qi", "m": "you're welcome; impolite", "pos": "", "lv": "YCT2,YCT3,HSK1,New HSK1"},
  {"id": 15, "w": "不要", "p": "bú yào", "m": "don't want", "pos": "副", "lv": "New HSK1"},
  {"id": 16, "w": "菜", "p": "cài", "m": "vegetable", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 17, "w": "茶", "p": "chá", "m": "tea", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 18, "w": "唱", "p": "chàng", "m": "sing", "pos": "动", "lv": "New HSK1"},
  {"id": 19, "w": "超市", "p": "chāo shì", "m": "supermarket", "pos": "名", "lv": "YCT4,HSK3,New HSK1"},
  {"id": 20, "w": "车", "p": "chē", "m": "car", "pos": "名", "lv": "New HSK1"},
  {"id": 21, "w": "吃", "p": "chī", "m": "to eat", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 22, "w": "出租车", "p": "chū zū chē", "m": "taxi", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 23, "w": "穿", "p": "chuān", "m": "to wear; to put on", "pos": "动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 24, "w": "大", "p": "dà", "m": "big", "pos": "形", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 25, "w": "打电话", "p": "dǎ diàn huà", "m": "to make a telephone call", "pos": "", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 26, "w": "大家", "p": "dà jiā", "m": "everybody", "pos": "代", "lv": "YCT4,HSK2,New HSK1"},
  {"id": 27, "w": "大学", "p": "dà xué", "m": "university", "pos": "名", "lv": "New HSK1"},
  {"id": 28, "w": "大学生", "p": "dà xué shēng", "m": "college student", "pos": "名", "lv": "New HSK1"},
  {"id": 29, "w": "到", "p": "dào", "m": "to arrive; to get to", "pos": "动", "lv": "HSK2,New HSK1"},
  {"id": 30, "w": "的", "p": "de", "m": "of", "pos": "助", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 31, "w": "第", "p": "dì", "m": "ordinal", "pos": "前缀", "lv": "New HSK1"},
  {"id": 32, "w": "弟弟", "p": "dì di", "m": "younger brother", "pos": "名", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 33, "w": "点", "p": "diǎn", "m": "point", "pos": "量", "lv": "YCT1,HSK1,New HSK1,New HSK2"},
  {"id": 34, "w": "店", "p": "diàn", "m": "shop", "pos": "名", "lv": "New HSK1"},
  {"id": 35, "w": "点儿", "p": "diǎn er", "m": "a little", "pos": "量", "lv": "New HSK1"},
  {"id": 36, "w": "电话", "p": "diàn huà", "m": "phone", "pos": "名", "lv": "New HSK1"},
  {"id": 37, "w": "电脑", "p": "diàn nǎo", "m": "computer", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 38, "w": "电视", "p": "diàn shì", "m": "TV", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 39, "w": "电影", "p": "diàn yǐng", "m": "film; movie", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 40, "w": "电影院", "p": "diàn yǐng yuàn", "m": "cinema", "pos": "名", "lv": "New HSK1"},
  {"id": 41, "w": "东西", "p": "dōng xi", "m": "thing", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 42, "w": "都", "p": "dōu", "m": "both; all", "pos": "副", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 43, "w": "读", "p": "dú", "m": "read aloud", "pos": "动", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 44, "w": "读书", "p": "dú shū", "m": "read  books", "pos": "动", "lv": "New HSK1"},
  {"id": 45, "w": "对", "p": "duì", "m": "correct; right", "pos": "形、介", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 46, "w": "对不起", "p": "duì bu qǐ", "m": "sorry", "pos": "动", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 47, "w": "多", "p": "duō", "m": "much/many; how [+adjective]", "pos": "形、代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 48, "w": "多少", "p": "duō shǎo", "m": "how much/many?", "pos": "代", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 49, "w": "二", "p": "èr", "m": "two", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 50, "w": "儿子", "p": "ér zi", "m": "son", "pos": "名", "lv": "YCT4,HSK1,New HSK1"},
  {"id": 51, "w": "饭", "p": "fàn", "m": "meal", "pos": "名", "lv": "New HSK1"},
  {"id": 52, "w": "饭店", "p": "fàn diàn", "m": "restaurant", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 53, "w": "房间", "p": "fáng jiān", "m": "room", "pos": "名", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 54, "w": "非常", "p": "fēi cháng", "m": "extremely", "pos": "副", "lv": "YCT4,HSK2,New HSK1"},
  {"id": 55, "w": "飞机", "p": "fēi jī", "m": "plane", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 56, "w": "分", "p": "fēn", "m": "minute", "pos": "量", "lv": "HSK3,New HSK1"},
  {"id": 57, "w": "分钟", "p": "fēn zhōng", "m": "minute", "pos": "量", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 58, "w": "高兴", "p": "gāo xìng", "m": "pleased; happy", "pos": "形", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 59, "w": "歌", "p": "gē", "m": "song", "pos": "名", "lv": "New HSK1"},
  {"id": 60, "w": "个", "p": "gè", "m": "individual; [general measure word]", "pos": "量", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 61, "w": "哥哥", "p": "gē ge", "m": "elder brother", "pos": "名", "lv": "YCT1,HSK2,New HSK1"},
  {"id": 62, "w": "给", "p": "gěi", "m": "to give", "pos": "动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 63, "w": "公司", "p": "gōng sī", "m": "company; office", "pos": "名", "lv": "HSK2,New HSK1"},
  {"id": 64, "w": "工作", "p": "gōng zuò", "m": "job; work", "pos": "动、名", "lv": "YCT4,HSK1,New HSK1"},
  {"id": 65, "w": "狗", "p": "gǒu", "m": "dog", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 66, "w": "贵", "p": "guì", "m": "expensive", "pos": "形", "lv": "YCT4,HSK2,New HSK1"},
  {"id": 67, "w": "国", "p": "guó", "m": "country", "pos": "名", "lv": "New HSK1"},
  {"id": 68, "w": "还", "p": "hái", "m": "even", "pos": "副", "lv": "YCT3,HSK2,HSK3,New HSK1,New HSK3"},
  {"id": 69, "w": "孩子", "p": "hái zi", "m": "child; children", "pos": "名", "lv": "YCT4,HSK2,New HSK1"},
  {"id": 70, "w": "汉语", "p": "hàn yǔ", "m": "Standard Chinese language", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 71, "w": "汉字", "p": "hàn zì", "m": "chinese character", "pos": "名", "lv": "New HSK1"},
  {"id": 72, "w": "好", "p": "hǎo", "m": "good", "pos": "形", "lv": "YCT1,HSK1,New HSK1,New HSK5"},
  {"id": 73, "w": "号", "p": "hào", "m": "number; day of a month", "pos": "名、量", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 74, "w": "好吃", "p": "hǎo chī", "m": "delicious", "pos": "形", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 75, "w": "好看", "p": "hǎo kàn", "m": "prettty", "pos": "形", "lv": "New HSK1"},
  {"id": 76, "w": "好听", "p": "hǎo tīng", "m": "pleasant", "pos": "形", "lv": "New HSK1"},
  {"id": 77, "w": "好玩儿", "p": "hǎo wán er", "m": "funny", "pos": "形", "lv": "New HSK1"},
  {"id": 78, "w": "喝", "p": "hē", "m": "to drink", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 79, "w": "和", "p": "hé", "m": "and", "pos": "介、连", "lv": "YCT1,HSK1,HSK7-9,New HSK1"},
  {"id": 80, "w": "很", "p": "hěn", "m": "very", "pos": "副", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 81, "w": "后", "p": "hòu", "m": "back", "pos": "名", "lv": "YCT3,New HSK1"},
  {"id": 82, "w": "回", "p": "huí", "m": "to return", "pos": "动", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 83, "w": "会", "p": "huì", "m": "can", "pos": "动", "lv": "YCT2,HSK1,New HSK1,New HSK3"},
  {"id": 84, "w": "火车", "p": "huǒ chē", "m": "train", "pos": "名", "lv": "YCT4,New HSK1"},
  {"id": 85, "w": "几", "p": "jǐ", "m": "how much/many? [expecting a small number]", "pos": "代、数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 86, "w": "鸡蛋", "p": "jī dàn", "m": "(chicken) egg", "pos": "名", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 87, "w": "家", "p": "jiā", "m": "family; home", "pos": "名、量", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 88, "w": "家人", "p": "jiā rén", "m": "family member", "pos": "名", "lv": "New HSK1"},
  {"id": 89, "w": "见", "p": "jiàn", "m": "see", "pos": "动", "lv": "New HSK1"},
  {"id": 90, "w": "件", "p": "jiàn", "m": "item; [measure word for items of clothing]", "pos": "量", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 91, "w": "叫", "p": "jiào", "m": "to call; to be named", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 92, "w": "饺子", "p": "jiǎo zi", "m": "dumpling", "pos": "名", "lv": "YCT3,HSK4,New HSK1"},
  {"id": 93, "w": "姐姐", "p": "jiě jie", "m": "elder sister", "pos": "名", "lv": "YCT1,HSK2,New HSK1"},
  {"id": 94, "w": "今年", "p": "jīn nián", "m": "this year", "pos": "名", "lv": "New HSK1"},
  {"id": 95, "w": "今天", "p": "jīn tiān", "m": "today", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 96, "w": "九", "p": "jiǔ", "m": "nine", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 97, "w": "觉得", "p": "jué de", "m": "to think; feel", "pos": "动", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 98, "w": "开", "p": "kāi", "m": "to switch on; open", "pos": "动", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 99, "w": "开车", "p": "kāi chē", "m": "drive", "pos": "动", "lv": "New HSK1"},
  {"id": 100, "w": "看", "p": "kàn", "m": "to see; to read; to watch; to look at", "pos": "动", "lv": "YCT1,HSK1,New HSK1,New HSK5"},
  {"id": 101, "w": "看病", "p": "kàn bìng", "m": "see a doctor", "pos": "动", "lv": "New HSK1"},
  {"id": 102, "w": "看见", "p": "kàn jiàn", "m": "see", "pos": "动", "lv": "HSK1,New HSK1"},
  {"id": 103, "w": "课", "p": "kè", "m": "lesson", "pos": "名", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 104, "w": "可以", "p": "kě yǐ", "m": "can; may", "pos": "动、形", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 105, "w": "口", "p": "kǒu", "m": "mouth; [measure word for family members]", "pos": "名、量", "lv": "YCT1,HSK3,New HSK1"},
  {"id": 106, "w": "块", "p": "kuài", "m": "lump; piece", "pos": "量", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 107, "w": "来", "p": "lái", "m": "to come", "pos": "动", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 108, "w": "老师", "p": "lǎo shī", "m": "teacher", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 109, "w": "了", "p": "le", "m": "[makes an exclamation]", "pos": "助", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 110, "w": "冷", "p": "lěng", "m": "cold", "pos": "形", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 111, "w": "里", "p": "lǐ", "m": "in", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 112, "w": "两", "p": "liǎng", "m": "two", "pos": "数", "lv": "YCT2,HSK2,New HSK1,New HSK4"},
  {"id": 113, "w": "零", "p": "líng", "m": "zero", "pos": "数", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 114, "w": "六", "p": "liù", "m": "six", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 115, "w": "吗", "p": "ma", "m": "[makes a yes; no question]", "pos": "助", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 116, "w": "妈妈", "p": "mā ma", "m": "mother", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 117, "w": "买", "p": "mǎi", "m": "buy", "pos": "动", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 118, "w": "卖", "p": "mài", "m": "to sell", "pos": "动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 119, "w": "忙", "p": "máng", "m": "busy", "pos": "形、动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 120, "w": "猫", "p": "māo", "m": "cat", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 121, "w": "没", "p": "méi", "m": "don't", "pos": "动、副", "lv": "New HSK1"},
  {"id": 122, "w": "没关系", "p": "méi guān xi", "m": "no problem", "pos": "", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 123, "w": "妹妹", "p": "mèi mei", "m": "younger sister", "pos": "名", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 124, "w": "没事", "p": "méi shì", "m": "it's ok", "pos": "动", "lv": "New HSK1"},
  {"id": 125, "w": "们", "p": "men", "m": "we", "pos": "后缀", "lv": "New HSK1"},
  {"id": 126, "w": "米饭", "p": "mǐ fàn", "m": "rice [cooked; boiled]", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 127, "w": "面包", "p": "miàn bāo", "m": "bread", "pos": "名", "lv": "YCT3,HSK3,New HSK1"},
  {"id": 128, "w": "面条儿", "p": "miàn tiáo er", "m": "noodle", "pos": "名", "lv": "New HSK1"},
  {"id": 129, "w": "明年", "p": "míng nián", "m": "next year", "pos": "名", "lv": "New HSK1"},
  {"id": 130, "w": "明天", "p": "míng tiān", "m": "tomorrow", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 131, "w": "名字", "p": "míng zi", "m": "given name", "pos": "名", "lv": "YCT2,YCT4,HSK1,New HSK1"},
  {"id": 132, "w": "哪", "p": "nǎ", "m": "which?", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 133, "w": "那", "p": "nà", "m": "that", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 134, "w": "那边", "p": "nà biān", "m": "that place", "pos": "代", "lv": "New HSK1"},
  {"id": 135, "w": "哪儿", "p": "nǎ er", "m": "where?", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 136, "w": "那儿", "p": "nà er", "m": "over there", "pos": "代", "lv": "YCT1,New HSK1"},
  {"id": 137, "w": "哪个", "p": "nǎ gè", "m": "which one", "pos": "代", "lv": "New HSK1"},
  {"id": 138, "w": "那个", "p": "nà gè", "m": "that one", "pos": "代", "lv": "New HSK1"},
  {"id": 139, "w": "哪里", "p": "nǎ lǐ", "m": "where", "pos": "代", "lv": "New HSK1"},
  {"id": 140, "w": "那里", "p": "nà lǐ", "m": "that", "pos": "代", "lv": "New HSK1"},
  {"id": 141, "w": "哪些", "p": "nǎ xiē", "m": "which", "pos": "代", "lv": "New HSK1"},
  {"id": 142, "w": "那些", "p": "nà xiē", "m": "those", "pos": "代", "lv": "New HSK1"},
  {"id": 143, "w": "男", "p": "nán", "m": "male", "pos": "形", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 144, "w": "男朋友", "p": "nán péng you", "m": "boyfriend", "pos": "名", "lv": "New HSK1"},
  {"id": 145, "w": "呢", "p": "ne", "m": "[returns; forwards a question]", "pos": "助", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 146, "w": "能", "p": "néng", "m": "to be able to; can", "pos": "动", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 147, "w": "你", "p": "nǐ", "m": "you", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 148, "w": "你好", "p": "nǐ hǎo", "m": "hello", "pos": "", "lv": "New HSK1"},
  {"id": 149, "w": "你们", "p": "nǐ men", "m": "you", "pos": "代", "lv": "New HSK1"},
  {"id": 150, "w": "年", "p": "nián", "m": "year", "pos": "名、量", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 151, "w": "您", "p": "nín", "m": "you [polite form]", "pos": "代", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 152, "w": "牛奶", "p": "niú nǎi", "m": "milk", "pos": "名", "lv": "YCT1,HSK2,New HSK1"},
  {"id": 153, "w": "女", "p": "nǚ", "m": "female", "pos": "形", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 154, "w": "女儿", "p": "nǚ ér", "m": "daughter", "pos": "名", "lv": "YCT4,HSK1,New HSK1"},
  {"id": 155, "w": "女朋友", "p": "nǚ péng you", "m": "girlfriend", "pos": "名", "lv": "New HSK1"},
  {"id": 156, "w": "女士", "p": "nǚ shì", "m": "lady; Madam; Miss", "pos": "名", "lv": "HSK5,New HSK1"},
  {"id": 157, "w": "朋友", "p": "péng you", "m": "friend", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 158, "w": "便宜", "p": "pián yi", "m": "cheap", "pos": "形", "lv": "YCT4,HSK2,New HSK1"},
  {"id": 159, "w": "漂亮", "p": "piào liang", "m": "beautiful", "pos": "形", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 160, "w": "苹果", "p": "píng guǒ", "m": "apple", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 161, "w": "七", "p": "qī", "m": "seven", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 162, "w": "起床", "p": "qǐ chuáng", "m": "get up (out of bed)", "pos": "动", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 163, "w": "千", "p": "qiān", "m": "thousand", "pos": "数", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 164, "w": "前", "p": "qián", "m": "front", "pos": "名", "lv": "YCT3,New HSK1"},
  {"id": 165, "w": "钱", "p": "qián", "m": "money", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 166, "w": "请", "p": "qǐng", "m": "to invite; please", "pos": "动", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 167, "w": "请问", "p": "qǐng wèn", "m": "excuse me", "pos": "动", "lv": "New HSK1"},
  {"id": 168, "w": "去", "p": "qù", "m": "to go", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 169, "w": "去年", "p": "qù nián", "m": "last year", "pos": "名", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 170, "w": "热", "p": "rè", "m": "hot", "pos": "形", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 171, "w": "人", "p": "rén", "m": "person; people", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 172, "w": "认识", "p": "rèn shi", "m": "to know [be familiar with]", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 173, "w": "日", "p": "rì", "m": "day [date]; sun", "pos": "量", "lv": "HSK2,New HSK1"},
  {"id": 174, "w": "三", "p": "sān", "m": "three", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 175, "w": "上", "p": "shàng", "m": "up; above", "pos": "名、动", "lv": "HSK1,New HSK1"},
  {"id": 176, "w": "上班", "p": "shàng bān", "m": "start work", "pos": "动", "lv": "YCT4,HSK2,New HSK1"},
  {"id": 177, "w": "商店", "p": "shāng diàn", "m": "shop", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 178, "w": "上课", "p": "shàng kè", "m": "have class", "pos": "动", "lv": "New HSK1"},
  {"id": 179, "w": "上午", "p": "shàng wǔ", "m": "morning", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 180, "w": "上学", "p": "shàng xué", "m": "go to school", "pos": "动", "lv": "New HSK1"},
  {"id": 181, "w": "少", "p": "shǎo", "m": "few", "pos": "形、动", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 182, "w": "谁", "p": "shéi", "m": "who?", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 183, "w": "什么", "p": "shén me", "m": "what?", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 184, "w": "生病", "p": "shēng bìng", "m": "ill; sick; unwell", "pos": "动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 185, "w": "十", "p": "shí", "m": "ten", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 186, "w": "事", "p": "shì", "m": "thing", "pos": "名", "lv": "New HSK1"},
  {"id": 187, "w": "是", "p": "shì", "m": "to be", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 188, "w": "时候", "p": "shí hou", "m": "[duration of] time", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 189, "w": "时间", "p": "shí jiān", "m": "time", "pos": "名", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 190, "w": "手机", "p": "shǒu jī", "m": "mobile phone", "pos": "名", "lv": "HSK2,New HSK1"},
  {"id": 191, "w": "书", "p": "shū", "m": "book", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 192, "w": "书店", "p": "shū diàn", "m": "bookshop", "pos": "名", "lv": "New HSK1"},
  {"id": 193, "w": "水", "p": "shuǐ", "m": "water", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 194, "w": "睡", "p": "shuì", "m": "sleep", "pos": "动", "lv": "New HSK1"},
  {"id": 195, "w": "水果", "p": "shuǐ guǒ", "m": "fruit", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 196, "w": "睡觉", "p": "shuì jiào", "m": "to go to bed; to sleep", "pos": "动", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 197, "w": "说", "p": "shuō", "m": "speak", "pos": "动", "lv": "HSK1,New HSK1"},
  {"id": 198, "w": "说话", "p": "shuō huà", "m": "speak", "pos": "动", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 199, "w": "四", "p": "sì", "m": "four", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 200, "w": "岁", "p": "suì", "m": "year (of crop harvests)", "pos": "量", "lv": "YCT1,YCT3,HSK1,New HSK1"},
  {"id": 201, "w": "他", "p": "tā", "m": "he; him", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 202, "w": "它", "p": "tā", "m": "it", "pos": "代", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 203, "w": "她", "p": "tā", "m": "she; her", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 204, "w": "他们", "p": "tā men", "m": "they", "pos": "代", "lv": "New HSK1"},
  {"id": 205, "w": "它们", "p": "tā men", "m": "they", "pos": "代", "lv": "New HSK1"},
  {"id": 206, "w": "她们", "p": "tā men", "m": "they", "pos": "代", "lv": "New HSK1"},
  {"id": 207, "w": "太", "p": "tài", "m": "very", "pos": "副", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 208, "w": "天", "p": "tiān", "m": "day", "pos": "名、量", "lv": "New HSK1"},
  {"id": 209, "w": "天气", "p": "tiān qì", "m": "weather", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 210, "w": "听", "p": "tīng", "m": "to listen; hear", "pos": "动", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 211, "w": "听见", "p": "tīng jiàn", "m": "hear", "pos": "动", "lv": "New HSK1"},
  {"id": 212, "w": "同学", "p": "tóng xué", "m": "schoolmate; classmate", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 213, "w": "外", "p": "wài", "m": "outside", "pos": "名", "lv": "HSK2,New HSK1"},
  {"id": 214, "w": "外边", "p": "wài biān", "m": "outside", "pos": "名", "lv": "New HSK1"},
  {"id": 215, "w": "玩", "p": "wán", "m": "to play", "pos": "动", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 216, "w": "晚", "p": "wǎn", "m": "evening", "pos": "形", "lv": "New HSK1"},
  {"id": 217, "w": "晚饭", "p": "wǎn fàn", "m": "dinner", "pos": "名", "lv": "New HSK1"},
  {"id": 218, "w": "晚上", "p": "wǎn shang", "m": "evening", "pos": "名", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 219, "w": "喂", "p": "wèi", "m": "hello", "pos": "叹", "lv": "YCT3,HSK1,HSK6,New HSK1,New HSK5"},
  {"id": 220, "w": "问", "p": "wèn", "m": "to ask", "pos": "动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 221, "w": "问题", "p": "wèn tí", "m": "problem", "pos": "名", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 222, "w": "我", "p": "wǒ", "m": "I; me", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 223, "w": "我们", "p": "wǒ men", "m": "we; us", "pos": "代", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 224, "w": "五", "p": "wǔ", "m": "five", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 225, "w": "午饭", "p": "wǔ fàn", "m": "lunch", "pos": "名", "lv": "New HSK1"},
  {"id": 226, "w": "喜欢", "p": "xǐ huan", "m": "to like", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 227, "w": "下", "p": "xià", "m": "down; below", "pos": "名、动、量", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 228, "w": "下班", "p": "xià bān", "m": "to get off work", "pos": "动", "lv": "New HSK1"},
  {"id": 229, "w": "下课", "p": "xià kè", "m": "get out of class", "pos": "动", "lv": "New HSK1"},
  {"id": 230, "w": "下午", "p": "xià wǔ", "m": "afternoon", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 231, "w": "下雨", "p": "xià yǔ", "m": "rain", "pos": "", "lv": "HSK1,New HSK1"},
  {"id": 232, "w": "先生", "p": "xiān sheng", "m": "Mr; Sir", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 233, "w": "现在", "p": "xiàn zài", "m": "now", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 234, "w": "想", "p": "xiǎng", "m": "to want; to think", "pos": "动", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 235, "w": "小", "p": "xiǎo", "m": "small", "pos": "形、前缀", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 236, "w": "小朋友", "p": "xiǎo péng you", "m": "child", "pos": "名", "lv": "New HSK1"},
  {"id": 237, "w": "小时", "p": "xiǎo shí", "m": "hour", "pos": "名", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 238, "w": "小学", "p": "xiǎo xué", "m": "primary school", "pos": "名", "lv": "New HSK1"},
  {"id": 239, "w": "小学生", "p": "xiǎo xué shēng", "m": "primary school student", "pos": "名", "lv": "New HSK1"},
  {"id": 240, "w": "些", "p": "xiē", "m": "some", "pos": "量", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 241, "w": "写", "p": "xiě", "m": "to write", "pos": "动", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 242, "w": "谢谢", "p": "xiè xie", "m": "thank you", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 243, "w": "新", "p": "xīn", "m": "new", "pos": "形", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 244, "w": "星期", "p": "xīng qī", "m": "week", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 245, "w": "星期日", "p": "xīng qī rì", "m": "sunday", "pos": "名", "lv": "New HSK1"},
  {"id": 246, "w": "星期天", "p": "xīng qī tiān", "m": "sunday", "pos": "名", "lv": "New HSK1"},
  {"id": 247, "w": "休息", "p": "xiū xi", "m": "to rest", "pos": "动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 248, "w": "学", "p": "xué", "m": "study", "pos": "动", "lv": "New HSK1"},
  {"id": 249, "w": "雪", "p": "xuě", "m": "snow", "pos": "名", "lv": "HSK2,New HSK1"},
  {"id": 250, "w": "学生", "p": "xué sheng", "m": "student", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 251, "w": "学习", "p": "xué xí", "m": "to learn; to study", "pos": "动", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 252, "w": "学校", "p": "xué xiào", "m": "school", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 253, "w": "要", "p": "yào", "m": "want; be going to; ask for; demand", "pos": "动", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 254, "w": "也", "p": "yě", "m": "too; also", "pos": "副", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 255, "w": "一", "p": "yī", "m": "one; once; first; structural word between two of the same verb; as soon as; throughout", "pos": "数", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 256, "w": "一半", "p": "yī bàn", "m": "half", "pos": "数", "lv": "New HSK1"},
  {"id": 257, "w": "衣服", "p": "yī fu", "m": "clothes", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 258, "w": "医生", "p": "yī shēng", "m": "doctor", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 259, "w": "一下", "p": "yī xià", "m": "[used after a verb] give something a go", "pos": "数量", "lv": "HSK2,New HSK1"},
  {"id": 260, "w": "一些", "p": "yī xiē", "m": "some", "pos": "数量", "lv": "New HSK1"},
  {"id": 261, "w": "医院", "p": "yī yuàn", "m": "hospital", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 262, "w": "椅子", "p": "yǐ zi", "m": "chair", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 263, "w": "有", "p": "yǒu", "m": "to have", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 264, "w": "有的", "p": "yǒu de", "m": "some", "pos": "代", "lv": "New HSK1"},
  {"id": 265, "w": "有点儿", "p": "yǒu diǎn er", "m": "a little", "pos": "副", "lv": "New HSK1"},
  {"id": 266, "w": "有些", "p": "yǒu xiē", "m": "some", "pos": "代", "lv": "New HSK1"},
  {"id": 267, "w": "雨", "p": "yǔ", "m": "rain", "pos": "名", "lv": "New HSK1"},
  {"id": 268, "w": "元", "p": "yuán", "m": "yuan [unit of Chinese currency]; dollar", "pos": "量", "lv": "YCT4,HSK3,New HSK1"},
  {"id": 269, "w": "月", "p": "yuè", "m": "month; moon", "pos": "名", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 270, "w": "再", "p": "zài", "m": "again", "pos": "副", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 271, "w": "在", "p": "zài", "m": "in; at; on", "pos": "动、介、副", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 272, "w": "再见", "p": "zài jiàn", "m": "goodbye", "pos": "动", "lv": "YCT1,HSK1,New HSK1"},
  {"id": 273, "w": "早", "p": "zǎo", "m": "early", "pos": "形", "lv": "New HSK1"},
  {"id": 274, "w": "早饭", "p": "zǎo fàn", "m": "breakfast", "pos": "名", "lv": "New HSK1"},
  {"id": 275, "w": "早上", "p": "zǎo shang", "m": "early morning", "pos": "名", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 276, "w": "怎么", "p": "zěn me", "m": "how?", "pos": "代", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 277, "w": "怎么样", "p": "zěn me yàng", "m": "how about it", "pos": "代", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 278, "w": "找", "p": "zhǎo", "m": "to find; to look for", "pos": "动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 279, "w": "这", "p": "zhè", "m": "this", "pos": "代", "lv": "YCT1,YCT4,HSK1,New HSK1"},
  {"id": 280, "w": "这边", "p": "zhè biān", "m": "this way", "pos": "代", "lv": "New HSK1"},
  {"id": 281, "w": "这儿", "p": "zhè er", "m": "here", "pos": "代", "lv": "YCT1,New HSK1"},
  {"id": 282, "w": "这个", "p": "zhè gè", "m": "this", "pos": "代", "lv": "New HSK1"},
  {"id": 283, "w": "这里", "p": "zhè lǐ", "m": "here", "pos": "代", "lv": "New HSK1"},
  {"id": 284, "w": "这些", "p": "zhè xiē", "m": "these", "pos": "代", "lv": "New HSK1"},
  {"id": 285, "w": "真", "p": "zhēn", "m": "real; so (+adjective)", "pos": "副", "lv": "YCT2,HSK2,New HSK1"},
  {"id": 286, "w": "正在", "p": "zhèng zài", "m": "to be in the process of", "pos": "副", "lv": "YCT4,HSK2,New HSK1"},
  {"id": 287, "w": "只", "p": "zhī", "m": "individual [measure word for small animals]", "pos": "量", "lv": "YCT2,HSK2,HSK3,New HSK1,New HSK3"},
  {"id": 288, "w": "知道", "p": "zhī dào", "m": "know; realise; be aware of", "pos": "动", "lv": "YCT3,HSK2,New HSK1"},
  {"id": 289, "w": "中国", "p": "zhōng guó", "m": "China", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 290, "w": "中文", "p": "zhōng wén", "m": "Chinese [written language]", "pos": "名", "lv": "HSK3,New HSK1"},
  {"id": 291, "w": "中午", "p": "zhōng wǔ", "m": "midday", "pos": "名", "lv": "YCT3,HSK1,New HSK1"},
  {"id": 292, "w": "中学", "p": "zhōng xué", "m": "middle school", "pos": "名", "lv": "New HSK1"},
  {"id": 293, "w": "中学生", "p": "zhōng xué shēng", "m": "middle school student", "pos": "名", "lv": "New HSK1"},
  {"id": 294, "w": "住", "p": "zhù", "m": "to live; stay (a number of nights)", "pos": "动", "lv": "YCT4,HSK1,New HSK1"},
  {"id": 295, "w": "桌子", "p": "zhuō zi", "m": "table", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 296, "w": "字", "p": "zì", "m": "(Chinese) character", "pos": "名", "lv": "HSK1,New HSK1"},
  {"id": 297, "w": "坐", "p": "zuò", "m": "to sit", "pos": "动", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 298, "w": "做", "p": "zuò", "m": "to do; to be; become (an occupation)", "pos": "动", "lv": "YCT2,HSK1,New HSK1"},
  {"id": 299, "w": "做饭", "p": "zuò fàn", "m": "cooking", "pos": "", "lv": "New HSK1"},
  {"id": 300, "w": "昨天", "p": "zuó tiān", "m": "yesterday", "pos": "名", "lv": "YCT2,HSK1,New HSK1"},
];